---


TrainingConfig:
  batch_size: 32
  epochs: 200
  lr: 0.001
  use_data_augmentations: true
  dataset_folder: '~/challenge-ens/data/v1_dataset'
  xp_rootdir: '~/challenge-ens/code/experiments'


InferenceConfig:
  batch_size: 32
  checkpoint_epoch: 84
  dataset_folder: '~/challenge-ens/data/v1_dataset'
  xp_rootdir: '~/challenge-ens/code/experiments'
